### PR TITLE
Improved docs

### PR DESCRIPTION
**Pull request by iloveitaly**

### CODE REVIEW

**Comment by iloveitaly** [comment]
@kbrw friendly bump on this! Any interest in adding me as a contributor to the GitHub and Hex projects so I can help maintain?

**Comment by iloveitaly** [comment]
@kbrw @awetzel @ma2gedev friendly bump on this! Any interest in adding me as a contributor to the GitHub and Hex projects so I can help maintain?

**Comment by iloveitaly** [comment]
@kbrw @awetzel @ma2gedev friendly reminder here!

**Comment by GuillaumeMilan** [comment]
Hello, I will discuss it internally with @Shakadak and @awetzel but I think we will refuse to add the tool version file in it.
I suggest you to redo the pull request without the file.

**Comment by iloveitaly** [comment]
@GuillaumeMilan curious, why is that the case?

**Comment by Shakadak** [comment]
Hi @iloveitaly, sorry for the delay, here's my point of view:
this PR does two thing, improving the documentation, and locking the local development environment to a specific version of elixir and implicitly erlang. Obviously anyone can change the file, manually or via the appropriate lines of command, but this is unneeded friction.
Furthermore, we would like to keep PRs scoped to one issue, and with minimal diff changes, in order to make it easier to follow what happened to the code using directly git logs. That's also why we refuse `mix format` changes on the current Kbrw's repositories.

---
Regarding the GitHub contributor question: You are free to bring up problems and possible improvements through GitHub's issues, discuss how it can be worked, and afterward implement the agreed upon solution, then open a pull request.
For the Hex ownership question: in my opinion, we will keep full control to Kbrw.

I understand though that Kbrw was really unresponsive in the past, and that this issue still needs improvement, and we appreciate every contribution. I think one part of the improvements needed will be aimed toward streamlining the contribution process.

**Pull request merged**
